url: http://www.ausdreamproperty.com

title: AUSDREAM

keywords: AUSDREAM

description: AUSDREAM

url-sunnybank-hills: http://www.parchomes.com.au/sunnybankhills/

exclude:
  - README.md

assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/js
    - _assets/css
  compress:
    css: true
    js: true
  gzip: []
