url: http://www.ausdreamproperty.com

title: AUSDREAM

keywords: AUSDREAM

description: AUSDREAM

url-sunnybank-hills: http://www.parchomes.com.au/sunnybankhills/

exclude:
  - README.md
  - style.css
  - style.js
